port: 3000
secret: this-is-secret
debug: true
database: 
  url: postgres://shin:passwd@localhost:5432/shin?sslmode=disable
  sqldir: src/sql
  migrations: src/sql/migrations
sendgrid:
  url: "url"
  api_key: "api_key"