env: "[development/test/production]"
port: 3000
secret: this-is-secret
fronthost: "devapp.shinid.com"
sso: # This should be same on the socious platform to bind trust token
  secret: sec
debug: true
database: 
  url: postgres://shin:passwd@localhost:5432/shin?sslmode=disable
  sqldir: src/sql
  migrations: src/sql/migrations
sendgrid:
  disabled: "[true/false]"
  url: "url"
  api_key: "api_key"
storage:
  type: "[GCS/AWS]"
  s3:
    access_key_id: access_key_id
    secret_access_key: secret_access_key
    default_region: ap-northeast-1
    bucket: shin-s3
    cdn_url: https://shin-s3.s3.ap-northeast-1.amazonaws.com
  gcs:
    bucket: shin-gcs
    cdn_url: https://storage.googleapis.com/shin-gcs
    credentials_path: ./gcs-service-account.json
cors:
  origins:
    - '*'
wallet:
  agent: "AGENT_URL"
  agent_api_key: "AGENT_API_KEY"
  connect: "CONNECT_TO_WALLET_URL"
nats:
  url: nats://127.0.0.1:4222
  secret: secret
logger:
  discord:
    shin_channel: "SHIN_CHANNEL_URL"
    shin_kyb_channel: "KYB_CHANNEL"
admin:
  access_token: "admin_access_token"