env: "[development/test/production]"
port: 3000
secret: this-is-secret
debug: true
database: 
  url: postgres://shin:passwd@localhost:5432/shin?sslmode=disable
  sqldir: src/sql
  migrations: src/sql/migrations
sendgrid:
  url: "url"
  api_key: "api_key"
s3:
  access_key_id: access_key_id
  secret_access_key: secret_access_key
  default_region: default_region
  bucket: default_region
  cdn_url: https://BUCKET.s3.DEFAULT_REGION.amazonaws.com
cors:
  origins:
    - '*'
logger:
  discord:
    shin_channel: "URL"