openapi: 3.0.0
info:
  title: Shin Project Docs
  version: 1.0.0
  description: Shin Project Docs
servers:
  - url: https://dev.shinid.com/
    description: Development server (uses test data)
  - url: https://api.shinid.com/
    description: Production server (uses live data)
  - url: http://localhost:3000/
    description: Local server (for development perposes)
paths:
  /auth/login:
    post:
      summary: Login the user
      description: Login the user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: 'string'
                  example: 'example@shin.com'
                password:
                  type: 'string'
                  example: 'P@$wd123'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
  /auth/register:
    post:
      summary: Register the user
      description: Register the user
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: 'string'
                  example: 'example@shin.com'
                password:
                  type: 'string'
                  example: 'P@$wd123'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
  /auth/refresh:
    post:
      summary: Refresh Access Token
      description: Will refresh the user's tokens
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: 'string'
                  example: 'example@shin.com'
                password:
                  type: 'string'
                  example: 'P@$wd123'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
  /auth/otp:
    post:
      summary: Send OTP
      description: Send OTP and resend it by this API
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: 'string'
                  example: 'example@shin.com'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
  /auth/otp/verify:
    post:
      summary: Verify OTP
      description: Verify OTP and fetch the new tokens 
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: 'string'
                  example: 'example@shin.com'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tokens'
  /auth/password/forget:
    post:
      summary: Send Forget Password OTP
      description: Send Forget Password OTP and resend it by this API
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: 'string'
                  example: 'example@shin.com'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
  /auth/password/update:
    post:
      summary: Change password
      description: Change password directly through forget password or with current password
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: 'string'
                  required: true
                  example: 'example@shin.com'
                current_password:
                  type: 'string'
                  required: false
                  example: 'example@shin.com'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
  /auth/pre-register:
    post:
      summary: Pre Register Process
      description: Checks weather if username or email that provided is available
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: 'string'
                  example: 'example@shin.com'
                username:
                  type: 'string'
                  example: 'exampleu'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: 'string'
                    enum:
                      - AVAILABLE
                      - EXISTS
                  username:
                    type: 'string'
                    enum:
                      - AVAILABLE
                      - EXISTS
  /integrations/keys:
    get:
      summary: Get All Keys
      description: Fetch all of the integration keys for current user
      tags:
        - Integration
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  limit:
                    type: number
                  page:
                    type: number
                  total:
                    type: number
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/IntegrationKey'
    post:
      summary: Create a Key
      description: Create a integration key for current user
      tags:
        - Integration
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: 'string'
                  example: 'Key Name'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrationKey'
  /integrations/keys/{key_id}:
    put:
      summary: Update a Key
      description: Update the integration key for current user
      tags:
        - Integration
      security:
        - bearerAuth: []
      parameters:
        - name: key_id
          in: path
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: 'string'
                  example: 'Key Name'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IntegrationKey'
    delete:
      summary: Delete a Key
      description: Delete the integration key for current user
      tags:
        - Integration
      security:
        - bearerAuth: []
      parameters:
        - name: key_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    Tokens:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string

    IntegrationKey:
      type: object
      properties:
        id:
          type: string
          example: 339ac66a-e18d-4622-904b-4929541995ff
        name:
          type: string
          example: Key Name
        key:
          type: string
          example: wy43fFdRW-u-tlhhSQCK0Yd24Qy7bYFEIS-tI9AjM54=
        secret:
          type: string
          example: pE8GsvI2MTTeBFVlPSg1fzqSLm4Alv_GQ8FBpEHZb-_XQoeoWbLVGVGsbiF8As-AKzTKZSphwHjviZeUDa-l-Q==
        base_url:
          type: string
          example: http://localhost:3000
        status:
          type: string
          enum: 
              - ACTIVE
              - SUSPENDED
          example: ACTIVE
        created_at:
          type: string
          example: 2024-10-13T21:06:58.923694Z
  