name: Docker

on:
  push:
    branches: ["main", "production", "feat/automation/add-workflows-docker"]
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}

jobs:

  test-build-dev:
    if:  github.event_name == 'push'
    name: Test & Build for Development env
    runs-on: ["backend-dev"]
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copying test and build environment
        run: |
          cp /etc/shin-api/test.config.yml .
          cp /etc/shin-api/config.yml .

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.22.5'
            
      - name: Downloading dependencies
        run: |
          go mod download

      - name: Running integration/unit tests
        run: |
          go test -v ./tests

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3.6.1

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-dev:
    needs: [test-build-dev]
    name: Deploy to Dev
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ["backend-dev-new"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with:
          go-version: '1.22.5'

      - name: Run DB migrations
        run: |
          go run cmd/migrate/main.go up

      - name: Docker run
        run: |
          docker pull ${{ steps.meta.outputs.tags }}
          docker ps -qa --filter "name=shin-api" | grep -q . && docker stop shin-api && docker rm -fv shin-api
          docker run -d --restart always -p 5061:5061 -h shin-api --network shinapi_default --name shin-api ${{ steps.meta.outputs.tags }}